---
- name: Restart designated service(s) for systemd network changes
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  listen: "linux_systemd_network_restart"
  loop: "{{ linux_systemd_network_responsible_services }}"
  when:
    - linux_systemd_network_apply_changes | type_debug == 'list'
    - linux_systemd_network_apply_changes | length > 0
