---
- name: Apply network interfaces changes via systemd service module
  become: true
  ansible.builtin.systemd_service:
    daemon_reexec: "{{ service.daemon_reexec | default(omit) }}"
    daemon_reload: "{{ service.daemon_reload | default(omit) }}"
    enabled: "{{ service.enabled | default(omit) }}"
    force: "{{ service.force | default(omit) }}"
    masked: "{{ service.masked | default(omit) }}"
    name: "{{ service.name }}"
    no_block : "{{ service.no_block | default(omit) }}"
    scope: "{{ service.scope | default(omit) }}"
    state: "{{ service.state | default(omit) }}"
  vars:
    service: "{{ network__interfaces_change_strategy | aybarsm.helper.replace_aliases(__ansible.modules.ansible_builtin_systemd_service.aliases) }}"
  register: network__interfaces_apply_changes_systemd_service
  listen: "network__interfaces_apply_changes"
  when:
    - network__interfaces_change_strategy.module is defined
    - network__interfaces_change_strategy.module == 'systemd_service'

- name: Apply network interfaces changes via service module
  become: true
  ansible.builtin.service:
    arguments: "{{ service.arguments | default(omit) }}"
    enabled: "{{ service.enabled | default(omit) }}"
    name: "{{ service.name }}"
    pattern: "{{ service.pattern | default(omit) }}"
    runlevel: "{{ service.runlevel | default(omit) }}"
    sleep: "{{ service.sleep | default(omit) }}"
    state: "{{ service.state | default(omit) }}"
    use: "{{ service.use | default(omit) }}"
  vars:
    service: "{{ network__interfaces_change_strategy | aybarsm.helper.replace_aliases(__ansible.modules.ansible_builtin_service.aliases) }}"
  register: network__interfaces_apply_changes_service
  listen: "network__interfaces_apply_changes"
  when:
    - network__interfaces_change_strategy.module is defined
    - network__interfaces_change_strategy.module == 'service'

- name: Apply network interfaces changes via command module
  become: true
  ansible.builtin.command:
    chdir: "{{ item.chdir | default(omit) }}"
    cmd: "{{ item.cmd }}"
    creates: "{{ item.creates | default(omit) }}"
    removes: "{{ item.removes | default(omit) }}"
    stdin: "{{ item.stdin | default(omit) }}"
    stdin_add_newline: "{{ item.stdin_add_newline | default(omit) }}"
    strip_empty_ends: "{{ item.strip_empty_ends | default(omit) }}"
  loop: "{{ network__interfaces_change_strategy.cmds | default([network__interfaces_change_strategy]) }}"
  changed_when: true
  register: network__interfaces_apply_changes_command
  listen: "network__interfaces_apply_changes"
  when:
    - network__interfaces_change_strategy.module is defined
    - network__interfaces_change_strategy.module == 'command'

- name: Apply systemd network changes via systemd service module
  become: true
  ansible.builtin.systemd_service:
    daemon_reexec: "{{ service.daemon_reexec | default(omit) }}"
    daemon_reload: "{{ service.daemon_reload | default(omit) }}"
    enabled: "{{ service.enabled | default(omit) }}"
    force: "{{ service.force | default(omit) }}"
    masked: "{{ service.masked | default(omit) }}"
    name: "{{ service.name }}"
    no_block : "{{ service.no_block | default(omit) }}"
    scope: "{{ service.scope | default(omit) }}"
    state: "{{ service.state | default(omit) }}"
  vars:
    service: "{{ network__systemd_change_strategy | aybarsm.helper.replace_aliases(__ansible.modules.ansible_builtin_systemd_service.aliases) }}"
  register: network__systemd_apply_changes_systemd_service
  listen: "network__systemd_apply_changes"
  when:
    - network__systemd_change_strategy.module is defined
    - network__systemd_change_strategy.module == 'systemd_service'

- name: Apply systemd network changes via command module
  become: true
  ansible.builtin.command:
    chdir: "{{ item.chdir | default(omit) }}"
    cmd: "{{ item.cmd }}"
    creates: "{{ item.creates | default(omit) }}"
    removes: "{{ item.removes | default(omit) }}"
    stdin: "{{ item.stdin | default(omit) }}"
    stdin_add_newline: "{{ item.stdin_add_newline | default(omit) }}"
    strip_empty_ends: "{{ item.strip_empty_ends | default(omit) }}"
  loop: "{{ network__systemd_change_strategy.cmds | default([network__systemd_change_strategy]) }}"
  register: network__systemd_apply_changes_command
  listen: "network__systemd_apply_changes"
  when:
    - network__systemd_change_strategy.module is defined
    - network__systemd_change_strategy.module == 'command'