---
linux_manage_grub: false

linux_grub_cfg_dir: /etc/default/grub.d
linux_grub_cfg_file: 50-ansible.cfg

linux_grub_backup_cfg_file: true
linux_grub_cfg_template: grub.cfg.j2

linux_grub_apply_changes: false
linux_grub_update_commands:
  - update-grub

linux_grub_config_name_prefix: GRUB_

linux_grub_inherit_cmdline_default: true
linux_grub_inherit_cmdline: true

linux_grub_config_default: []
linux_grub_config_group: []
linux_grub_config_host: []
linux_grub_config_all: "{{ [linux_grub_config_default, linux_grub_config_group, linux_grub_config_host] |
  community.general.lists_mergeby('name', recursive=true, list_merge='prepend') |
  unique_recursive(attribute='name', recurse='value') }}"

__linux_grub_cfg_destination: "{{ linux_grub_cfg_dir + '/' + linux_grub_cfg_file }}"
