---
grub__role_enabled: false

grub__file: /etc/default/grub.d/50-ansible.cfg
grub__template: etc/default/grub.d/grub.cfg.j2
grub__backup: true

grub__inherit_cmdlines: true

grub__change_strategy:
# Available modules: command
# Set module other than available options to disable applying changes
  module: command
# immediate can be true or false (Flushes the handlers immediately)
  immediate: false
  cmd: 'update-grub'

grub__default: []
grub__group: []
grub__host: []
