---
- name: Manage Proxmox Datacenter ACLs
  aybarsm.linux.proxmox_acl:
    path: "{{ item.path }}"
    roles: "{{ item.roles }}"
    state: "{{ item.state | default('present') }}"
    groups: "{{ item.groups | default([]) }}"
    users: "{{ item.users | default([]) }}"
  loop: "{{ proxmox_datacenter_acls }}"
  register: proxmox__apply_datacenter_acls