---
- name: Manage Proxmox Datacenter User Groups
  aybarsm.linux.proxmox_group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ proxmox_datacenter_user_groups }}"
  register: proxmox__apply_datacenter_user_groups