---
- name: Manage system packages with common package manager
  ansible.builtin.package:
    name: "{{ package_name }}"
    state: "{{ item.state | default(omit) }}"
    use: "{{ item.use | default(omit) }}"
  vars:
    package_name: "{{ item.name + '=' + item.version if 'version' in item else item.name }}"
  register: linux_package_manager_common_packages_apply
  when:
    - linux_packages_all | type_debug == 'list'
    - linux_packages_all | selectattr('type', 'defined') | selectattr('type', 'equalto', 'package') | length > 0
  loop: "{{ linux_packages_all | selectattr('type', 'defined') | selectattr('type', 'equalto', 'package') | length > 0 }}"
