---
- name: Manage system packages with common package manager
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    use: "{{ item.use | default(omit) }}"
  register: package_manager__common_packages_apply
  when:
    - linux_packages_all | type_debug == 'list'
    - linux_packages_all | length > 0
  loop: "{{ linux_packages_all }}"
