---
- name: Manage system packages with common package manager
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    use: "{{ item.use | default(omit) }}"
  register: package_manager__packages_common_apply
  when:
    - package_manager__packages_all | type_debug == 'list'
    - package_manager__packages_all | length > 0
  loop: "{{ package_manager__packages_all }}"
