---
- name: Perform DEB package upgrade via APT
  become: true
  ansible.builtin.apt:
    update_cache: "{{ package_manager__upgrade_update_repo_cache | default(omit) | bool }}"
    upgrade: "{{ upgrade_mode }}"
    dpkg_options: "{{ package_manager__upgrade_dpkg_options | default(omit) }}"
  vars:
    upgrade_mode: "{{ package_manager__upgrade_mode | regex_replace('clean_', '') }}"
  register: package_manager__deb_upgrade
  when:
    - package_manager__upgrade_mode is defined
    - upgrade_mode in __package_manager__upgrade_modes