---
- name: Load OS related variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Load common variables structured on OS related variables
  ansible.builtin.include_vars: common.yml

- name: Import DEB repository and repository key tasks (APT)
  ansible.builtin.import_tasks:
    file: deb.yml
  when:
    - linux_role_package_manager_enabled | default(false) | bool
    - ansible_os_family | lower == 'debian'

- name: Simulate DEB package tasks (APT)
  ansible.builtin.import_tasks:
    file: deb_packages.yml
  vars:
    __linux_package_manager_simulate_packages: true
  when:
    - linux_role_package_manager_enabled | default(false) | bool
    - linux_package_manager_package_strategy | lower == 'specific'
    - ansible_os_family | lower == 'debian'
    - linux_package_manager_package_simulation | default(true) | bool
    - not ansible_check_mode

- name: Import DEB package tasks (APT)
  ansible.builtin.import_tasks:
    file: deb_packages.yml
  when:
    - linux_role_package_manager_enabled | default(false) | bool
    - linux_package_manager_package_strategy | lower == 'specific'
    - ansible_os_family | lower == 'debian'

- name: Import common package manager tasks
  ansible.builtin.import_tasks:
    file: common_packages.yml
  when:
    - linux_role_package_manager_enabled | default(false) | bool
    - linux_package_manager_package_strategy | lower == 'common'
