---
- name: Load OS family related variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Load common variables structured on OS related variables
  ansible.builtin.include_vars: common.yml

- name: Include DEB repository key and repository tasks (APT)
  ansible.builtin.include_tasks:
    file: deb_repo.yml
  when:
    - package_manager__role_enabled | default(false) | bool
    - ansible_os_family | default('') | lower == 'debian'

# TODO: Implement RPM repository tasks
# - name: Include RPM repository repository tasks (YUM)
#   ansible.builtin.include_tasks:
#     file: rpm_repo.yml
#   when:
#     - package_manager__role_enabled | default(false) | bool
#     - ansible_os_family | default('') | lower == 'redhat'

- name: Include upgrade tasks
  ansible.builtin.include_tasks:
    file: upgrade.yml
  when:
    - package_manager__role_enabled | default(false) | bool
    - __package_manager__upgrade_execute.decision
  vars:
    ansible_callback_diy_runner_on_skipped_msg: |
      skipping: [{{ inventory_hostname }}]
      msg: {{ __package_manager__upgrade_execute.reason }}

- name: Include DEB package tasks (APT)
  ansible.builtin.include_tasks:
    file: deb_packages.yml
  when:
    - package_manager__role_enabled | default(false) | bool
    - package_manager__package_strategy | lower == 'specific'
    - ansible_os_family | default('') | lower == 'debian'

- name: Include RPM package tasks (DNF)
  ansible.builtin.include_tasks:
    file: rpm_packages.yml
  when:
    - package_manager__role_enabled | default(false) | bool
    - package_manager__package_strategy | lower == 'specific'
    - ansible_os_family | default('') | lower == 'redhat'

- name: Include common package manager tasks
  ansible.builtin.include_tasks:
    file: common_packages.yml
  when:
    - package_manager__role_enabled | default(false) | bool
    - package_manager__package_strategy | lower == 'common'
