---
- name: Set facts for package manager role
  ansible.builtin.set_fact:
    __package_manager__upgrade_once_eligible: "{{ upgrade_once_eligible }}"
    __package_manager__upgrade_perform: "{{ is_upgrade_always or (is_upgrade_once and upgrade_once_eligible and not is_upgrade_defined) }}"
    __package_manager__upgrade_clean: "{{ package_manager__upgrade_mode in __package_manager__clean_upgrade_modes }}"
  vars:
    is_upgrade_once: "{{ package_manager__upgrade_strategy == 'once' }}"
    is_upgrade_always: "{{ package_manager__upgrade_strategy == 'always' }}"
    is_ansible_role: "{{ ansible__role_enabled | default(false) | bool }}"
    is_manage_local_facts: "{{ ansible__manage_local_facts | default(false) | bool }}"
    is_local_facts_defined: "{{ __ansible__local_facts is defined }}"
    is_upgrade_defined: "{{ __ansible__local_facts.package_manager.upgrade is defined }}"
    upgrade_once_eligible: "{{ is_ansible_role and is_manage_local_facts and is_local_facts_defined }}"
  register: package_manager__set_facts