network__all: "{{ (network__host + network__group + network__default) |
  map('aybarsm.helper.combine_reverse', {'keep__entry': true, 'skip__entry': false}) |
  rejectattr('keep__entry', 'eq', false) | rejectattr('skip__entry', 'eq', true) | rejectattr('type', 'undefined') |
  aybarsm.helper.all_except(['keep__entry', 'skip__entry']) }}"

##### BEGIN: network systemd vars
__network_systemd_available_change_modules: ['systemd_service', 'command']
__network__systemd_link_name: '{"type":"systemd","name":"__SYSTEMD_LINK_NAME__","children":[{"name":"Match","children":[{"name":"MACAddress","value":"__MAC_ADDRESS__"},{"name":"Type","value":"ether"}]},{"name":"Link","children":[{"name":"NamePolicy","value":""},{"name":"Name","value":"__LINK_NAME__"}]}]}'
__network__systemd_rename: >-
  {%- set __rtr = [] -%}
  {%- set __cfgs = (network__all | selectattr('type', 'eq', 'systemd_link_rename') |
  selectattr('name', 'defined') | selectattr('name', 'match', '^(?:[0-9]|[1-9][0-9])-[a-zA-Z]+\\d+\\.link$') |
  selectattr('macaddress', 'defined') | selectattr('macaddress', 'match', '^([0-9A-Fa-f]{2}([:])?){5}([0-9A-Fa-f]{2})$') | default([])) -%}
  {%- for cfg in __cfgs if cfg -%}
  {%-   set __rtr = __rtr.append(__network__systemd_link_name |
    replace('__SYSTEMD_LINK_NAME__', cfg.name) | replace('__MAC_ADDRESS__', cfg.macaddress) |
    replace('__LINK_NAME__', (cfg.name | regex_replace('^(?:[0-9]|[1-9][0-9])-(.*).link$', '\\1'))) | from_json) -%}
  {%- endfor -%}
  {{ __rtr }}

network__systemd_all: "{{ ((network__all | selectattr('type', 'eq', 'systemd') |
  selectattr('name', 'defined') | selectattr('name', 'search', '\\.(network|link|netdev)$') |
  selectattr('children', 'defined') | default([])) + __network__systemd_rename) | reverse |
  community.general.lists_mergeby('name', recursive=true, list_merge='prepend') |
  aybarsm.helper.unique_recursive(attributes='name', recurse='children') }}"

__network__systemd_names: "{{ network__systemd_all | map(attribute='name') }}"
# REVIEW: There is room for optimisation
# Escape file names defined in network__systemd_all
__network__systemd_cleanup_regex:
  - "^({{ __network__systemd_names | select('match', '.*\\.link$') | map('replace', '.link', '') | join('|') }})\\.link$"
  - "^({{ __network__systemd_names | select('match', '.*\\.netdev$') | map('replace', '.netdev', '') | join('|') }})\\.netdev$"
  - "^({{ __network__systemd_names | select('match', '.*\\.network$') | map('replace', '.network', '') | join('|') }})\\.network$"
# Escape backup files:
  - "^.*\\.\\d+\\.\\d{4}-\\d{2}-\\d{2}@\\d{2}:\\d{2}:\\d{2}~$"

# Join regex expressions
network__systemd_cleanup_patterns: ["(?!{{ __network__systemd_cleanup_regex | join('|') }})"]
##### END: network systemd vars

##### BEGIN: network interfaces vars
__network_interfaces_available_change_modules: ['service', 'systemd_service', 'command']

# Sort interfaces by name to avoid unneccessary changes
network__interfaces_all: "{{ network__all | reverse |
  selectattr('type', 'eq', 'interface') | selectattr('name', 'defined') |
  community.general.lists_mergeby('name', recursive=true, list_merge='prepend') |
  aybarsm.helper.unique_recursive(attributes='name', recurse='inet') |
  aybarsm.helper.unique_recursive(attributes='name', recurse='inet6') |
  sort(attribute='name') }}"

##### BEGIN: network sysctl vars
network__sysctl_all: "{{ network__all |
  selectattr('type', 'defined') | selectattr('type', 'equalto', 'sysctl') |
  aybarsm.helper.replace_aliases(__ansible.modules.ansible_posix_sysctl.aliases) |
  selectattr('name', 'defined') | selectattr('value', 'defined') | unique(attribute='name') }}"
##### END: network sysctl vars

##### BEGIN: network hosts vars
__network__hosts_auto_discovered: >-
  {%- if (network__hosts_auto_discovery | default(false) | bool) and network__hosts_auto_discovery_inventories is defined and network__hosts_auto_discovery_inventories | length > 0 -%}
  {%-   set inventory_lookup = lookup('ansible.builtin.inventory_hostnames', network__hosts_auto_discovery_inventories) -%}
  {%-   if inventory_lookup | length > 0 -%}
  {%-     set inventory_hosts = inventory_lookup | split(',') -%}
  {%-     set discovered_hosts = dict(hostvars) | aybarsm.helper.only_with(inventory_hosts) | dict2items | selectattr('value.ansible_host', 'defined') -%}
  {%-     set ips = discovered_hosts | map(attribute='value.ansible_host') -%}
  {%-     set hostnames = discovered_hosts | map(attribute='value.inventory_hostname_short') -%}
  {%-     set fqdns = discovered_hosts | map(attribute='value.inventory_hostname') -%}
  {%-     set auto_discovered = {'ip': ips, 'hostname': hostnames, 'fqdn': fqdns} | aybarsm.helper.to_list_of_dicts({'type': 'host'}) -%}
  {%-   endif -%}
  {%- else -%}
  {%-   set auto_discovered = [] -%}
  {%- endif -%}
  {{ auto_discovered }}

network__hosts_all: "{{ (network__all + __network__hosts_auto_discovered) |
  selectattr('type', 'eq', 'host') | selectattr('ip', 'defined') | selectattr('hostname', 'defined') |
  aybarsm.helper.replace_aliases({'fqdn': ['hostname']}) | unique(attribute='ip') }}"

# Sort hosts by hostname to avoid unneccessary changes
network__hosts_all_ipv4: "{{ network__hosts_all | selectattr('ip', 'ansible.utils.ipv4') | sort(attribute='hostname') }}"
network__hosts_all_ipv6: "{{ network__hosts_all | selectattr('ip', 'ansible.utils.ipv6') | sort(attribute='hostname') }}"
##### END: network hosts vars

##### BEGIN: network iptables vars
network__iptables_all: "{{ network__all | selectattr('type', 'eq', 'iptables') }}"
##### END: network iptables vars

##### BEGIN: network udev rules vars
network__udev_rules_all: "{{ network__all | selectattr('type', 'eq', 'udev_rule') | selectattr('entries', 'defined') }}"
##### END: network udev rules vars