network__all: "{{ {'host': network__host, 'group': network__group, 'default': network__default} | aybarsm.helper.role_vars(only=network__use_only) }}"

##### BEGIN: network sysctl vars
network__sysctl_all: "{{ network__all | selectattr('entry__type', 'eq', 'sysctl') |
  aybarsm.helper.replace_aliases(__ansible.modules.ansible_posix_sysctl.aliases, removeAliases=true) |
  community.general.json_query('[?not_null(name) && not_null(value)]') |
  unique(attribute='name') }}"
##### END: network sysctl vars