---
- name: Manage APT Repository Keys
  become: true
  ansible.builtin.apt_key:
    state: "{{ item.state | default(omit) }}"
    data: "{{ item.data | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    keyring: "{{ item.keyring | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
  loop: "{{ repo_keys }}"
  register: pkg_mgr__apply_apt_repo_keys
