---
linux_manage_systemd_network: false

linux_systemd_network_apply_changes: []
# linux_systemd_network_apply_changes:
#   - service: systemd-networkd
#     state: restarted
#   - command: "systemctl daemon-reload"

linux_systemd_network_backup: true
linux_systemd_network_cleanup: false
linux_systemd_network_cleanup_patterns_use_regex: true

# Consult: https://manpages.debian.org/bookworm/systemd/systemd.net-naming-scheme.7.en.html
linux_systemd_network_naming_scheme: "v252"

linux_systemd_network_dir: /etc/systemd/network
linux_systemd_network_template: network.j2

linux_systemd_network_default: []
linux_systemd_network_group: []
linux_systemd_network_host: []
linux_systemd_network_all: "{{ (linux_systemd_network_host + linux_systemd_network_group + linux_systemd_network_default) |
  selectattr('name', 'defined') | selectattr('name', 'search', '\\.(network|link|netdev)$') |
  selectattr('config', 'defined') | unique(attribute='name') }}"

linux_systemd_network_names: "{{ linux_systemd_network_all | map(attribute='name') }}"
linux_systemd_network_cleanup_regex:
  - "^({{ linux_systemd_network_names | select('match', '.*\\.link$') | map('replace', '.link', '') | join('|') }})\\.link$"
  - "^({{ linux_systemd_network_names | select('match', '.*\\.netdev$') | map('replace', '.netdev', '') | join('|') }})\\.netdev$"
  - "^({{ linux_systemd_network_names | select('match', '.*\\.network$') | map('replace', '.network', '') | join('|') }})\\.network$"
# Escape backup files:
  - "^.*\\.\\d+\\.\\d{4}-\\d{2}-\\d{2}@\\d{2}:\\d{2}:\\d{2}~$"

linux_systemd_network_cleanup_patterns: ["(?!{{ linux_systemd_network_cleanup_regex | join('|') }})"]
