proxmox__role_enabled: false

proxmox__manage_repo_keys: false
proxmox__manage_repos: false
proxmox__manage_packages: false
proxmox__manage_grub: false
proxmox__manage_hostname: false
proxmox__manage_hosts: false
# This option force root user to generate ssh key and distribute to all hosts within the cluster
proxmox__manage_root_access: false
proxmox__manage_sshd_config: false
proxmox__manage_ssh_config: false
proxmox__manage_cluster: false

# Hostname and FQDN configuration
proxmox__hostname: "{{ inventory_hostname_short }}"
proxmox__domain: local

# Cluster configuration
# For target inventory specs, consult https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html for more information
# If init node not provided, the init node will be designated as the first node regarding ascending sorted of inventory_hostname
# proxmox__clusters variables has been designed to be managed from a single source of truth, i.e. group_vars/all.yml However, it can be overwritten from the host vars.
# proxmox__clusters:
#   - name: 'pve-london01'
#     target: 'proxmox:&london'
#   - name: 'pve-atlanta01'
#     target: 'proxmox:&atlanta'
#     init: 'pve01-atlanta01'
proxmox__clusters: []
# Ip addresses for the cluster links for the host
# i.e. proxmox__cluster_links: ['10.0.0.2', 'fd00::2']
# If more than one ip provided, the first link ip will be used as the cluster ip for the hosts file
proxmox__cluster_links: []

proxmox__ssh_port: 22
proxmox__ssh_ciphers: "aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com"
proxmox__remove_subscription_warning: false

proxmox__repo_url_enterprise: https://enterprise.proxmox.com/debian
proxmox__repo_url_no_subscription: http://download.proxmox.com/debian
proxmox__repo_keys:
  bookworm:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
    keyring: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
  bullseye:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    keyring: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg

proxmox__purpose_names: ['pve', 'pbs', 'pmg', 'ceph_pacific', 'ceph_quincy', 'ceph_reef', 'zfs']
proxmox__purpose_types: ['enterprise', 'no-subscription']
proxmox__purpose_packages:
  pve: ['pve-manager']
  pbs: ['proxmox-backup-server']
  pmg: ['proxmox-mailgateway']
  ceph_pacific: ['ceph', 'ceph-common', 'ceph-mds', 'ceph-fuse']
  ceph_quincy: ['ceph', 'ceph-common', 'ceph-mds', 'ceph-fuse']
  ceph_reef: ['ceph', 'ceph-common', 'ceph-mds', 'ceph-fuse']
  zfs: ['zfsutils-linux', 'zfs-initramfs', 'zfs-zed']

proxmox__default: {}
proxmox__group: {}
proxmox__host: {}

# Example configuration:
# Purposes will be overwritten by the host configuration.
# The type can be set other than the provided list to rule out.
## ZFS Consult with: https://pve.proxmox.com/wiki/ZFS_on_Linux#sysadmin_zfs_limit_memory_usage
## ZFS Consult with: https://pve.proxmox.com/wiki/ZFS_on_Linux#_configure_e_mail_notification
# proxmox__default:
#   purposes:
#     pve:
#       type: no-subscription
#       version: latest
# # ------------------------------------------------
# proxmox__host:
#   purposes:
#     pve:
#       type: no-subscription
#       version: 8.2.4
#     ceph_reef:
#       type: no-subscription
#     pbs:
#       type: no-subscription
#       version: 3.2.4-1
#     pmg:
#       type: no-subscription
#       version: 8.1.0
#     zfs:
#       version: 2.2.4-pve1
#       params: 'zfs_arc_max=2147483648'
#       zed_email: 'noc@example.com'
#       post_install: "{{ playbook_dir }}/tasks/zfs_post_install.yml"