proxmox__role_enabled: false

proxmox__repo_url_enterprise: https://enterprise.proxmox.com/debian
proxmox__repo_url_no_subscription: http://download.proxmox.com/debian

proxmox__purpose_names: ['pve', 'pbs', 'pmg', 'ceph-pacific', 'ceph-quincy', 'ceph-reef']
proxmox__purpose_types: ['enterprise', 'no-subscription']

# If enabled, the role will manage the purpose package setup for repos and package versioning.
proxmox__manage_purpose_package_setup: true
proxmox__purpose_package_setup_template: purpose_package_setup.j2

# proxmox__default: {}
# proxmox__group: {}
# proxmox__host: {}

# Example configuration:
# Purposes will be overwritten by the host configuration.
# The type can be set other than the provided list to rule out.
# proxmox__default:
#   purposes:
#     pve:
#       type: no-subscription
#       version: latest
# # ------------------------------------------------
# proxmox__group:
# proxmox__host:
#   purposes:
#     pve:
#       type: no-subscription
#       version: 8.2.4
#     ceph_reef:
#       type: no-subscription
#     pbs:
#       type: no-subscription
#       version: 3.2.4-1
#     pmg:
#       type: no-subscription
#       version: 8.1.0

# The combination strategy below is highly nested hierarchy compliant and recommended (Example provided below)
# proxmox__host > proxmox__group > proxmox__default
proxmox__all: "{{ proxmox__default | combine(proxmox__group, proxmox__host, recursive=true, list_merge=replace) }}"