proxmox__role_enabled: false

proxmox__repo_url_enterprise: https://enterprise.proxmox.com/debian
proxmox__repo_url_no_subscription: http://download.proxmox.com/debian

proxmox__default: {}
proxmox__group: {}
proxmox__host: {}

proxmox__all: "{{ proxmox__default | combine(proxmox__group, proxmox__host) }}"