---
- name: Find unexpected systemd-network files
  become: true
  ansible.builtin.find:
    paths: "{{ systemd__network_dir }}"
    patterns: "{{ systemd__network_cleanup_patterns }}"
    use_regex: "{{ systemd__network_cleanup_patterns_use_regex | bool }}"
  when: systemd__network_cleanup | bool
  register: systemd__network_find_cleanup_files

- name: Remove unexpected systemd-network files
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ systemd__network_find_cleanup_files.files | map(attribute='path') }}"
  when:
    - systemd__network_cleanup | bool
    - systemd__network_find_cleanup_files.files | length > 0
  register: systemd__network_cleanup_files
  notify: systemd__networkd_restart

- name: Deploy systemd-network files
  become: true
  ansible.builtin.template:
    src: "{{ systemd__network_template }}"
    dest: "{{ systemd__network_dir }}/{{ item.name }}"
    backup: "{{ systemd__network_backup | default(omit) | bool }}"
    mode: "0644"
  loop: "{{ systemd__network_all }}"
  when:
    - systemd__network_all | type_debug == 'list'
    - systemd__network_all | length > 0
  register: systemd__network_deploy_files
  notify: systemd__networkd_restart
