---
- name: Find unexpected systemd-network files
  become: true
  ansible.builtin.find:
    paths: "{{ linux_systemd_network_dir }}"
    patterns: "{{ linux_systemd_network_cleanup_patterns }}"
    use_regex: "{{ linux_systemd_network_cleanup_patterns_use_regex | bool }}"
  when: linux_systemd_network_cleanup | bool
  register: linux_systemd_network_find_cleanup_files

- name: Remove unexpected systemd-network files
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ linux_systemd_network_find_cleanup_files.files | map(attribute='path') }}"
  when:
    - linux_systemd_network_cleanup | bool
    - linux_systemd_network_find_cleanup_files.files | length > 0
  register: linux_systemd_network_cleanup_files
  notify: linux_systemd_networkd_restart

- name: Deploy systemd-network files
  become: true
  ansible.builtin.template:
    src: "{{ linux_systemd_network_template }}"
    dest: "{{ linux_systemd_network_dir }}/{{ item.name }}"
    backup: "{{ linux_systemd_network_backup | default(omit) | bool }}"
    mode: "0644"
  loop: "{{ linux_systemd_network_all }}"
  when:
    - linux_systemd_network_all | type_debug == 'list'
    - linux_systemd_network_all | length > 0
  register: linux_systemd_network_deploy_files
  notify: linux_systemd_networkd_restart
