hosts__role_enabled: false

hosts__dir: /etc
hosts__file: "{{ hosts__dir }}/hosts"
hosts__template: etc/hosts.j2
hosts__backup: true

# If enabled, the ansible inventory will be collected automatically
# and will be appended to the list of hosts, when ansible_host (ip address) is defined.
# ip: ansible_host, hostname: inventory_hostname_short, fqdn: inventory_hostname
hosts__auto_discovery: false
# Consult https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html for more information
hosts__auto_discovery_inventories: 'webservers:&atlanta'

hosts__default: []
hosts__group: []
hosts__host: []