---
- name: Deploy Proxmox cluster groups
  aybarsm.linux.proxmox_group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    comment: "{{ item.comment | default(omit) }}"
  with_items: "{{ __proxmox__cluster.groups }}"
  when: __proxmox__cluster.groups | default([]) | length > 0
  register: proxmox__cluster_groups_deploy