---
- name: Include Proxmox datacenter pool tasks
  ansible.builtin.include_tasks:
    file: datacenter/pool.yml
  loop: "{{ __proxmox__cluster.pools }}"
  loop_control:
    loop_var: proxmox__dc_pool
    index_var: proxmox__dc_pool_index
  when:
    - __proxmox__cluster.manage_pools | default(false) | bool
    - __proxmox__cluster.pools | default([]) | length > 0

- name: Include Proxmox datacenter role tasks
  ansible.builtin.include_tasks:
    file: datacenter/role.yml
  loop: "{{ __proxmox__cluster.roles }}"
  loop_control:
    loop_var: proxmox__dc_role
    index_var: proxmox__dc_role_index
  when:
    - __proxmox__cluster.manage_roles | default(false) | bool
    - __proxmox__cluster.roles | default([]) | length > 0

- name: Include Proxmox datacenter user group tasks
  ansible.builtin.include_tasks:
    file: datacenter/group.yml
  loop: "{{ __proxmox__cluster.groups }}"
  loop_control:
    loop_var: proxmox__dc_group
    index_var: proxmox__dc_group_index
  when:
    - proxmox__role_enabled
    - __proxmox__cluster.manage_groups | default(false) | bool
    - __proxmox__cluster.groups | default([]) | length > 0

- name: Include Proxmox datacenter user tasks
  ansible.builtin.include_tasks:
    file: datacenter/user.yml
  loop: "{{ __proxmox__cluster.users }}"
  loop_control:
    loop_var: proxmox__dc_user
    index_var: proxmox__dc_user_index
  when:
    - proxmox__role_enabled
    - __proxmox__cluster.manage_users | default(false) | bool
    - __proxmox__cluster.users | default([]) | length > 0

- name: Include Proxmox datacenter ACL tasks
  ansible.builtin.include_tasks:
    file: datacenter/acl.yml
  loop: "{{ __proxmox__cluster.acls }}"
  loop_control:
    loop_var: proxmox__dc_acl
    index_var: proxmox__dc_acl_index
  when:
    - proxmox__role_enabled
    - __proxmox__cluster.manage_acls | default(false) | bool
    - __proxmox__cluster.acls | default([]) | length > 0