---
- name: Include Proxmox Datacenter Pools Task
  ansible.builtin.include_tasks:
    file: datacenter/pools.yml
  vars:
    proxmox_datacenter_pools: "{{ proxmox__all | selectattr('entry__type', 'eq', 'pool') }}"
  when:
    - proxmox__manage_pools
    - proxmox_datacenter_pools | length > 0

- name: Include Proxmox Datacenter Roles Task
  ansible.builtin.include_tasks:
    file: datacenter/roles.yml
  vars:
    proxmox_datacenter_roles: "{{ proxmox__all | selectattr('entry__type', 'eq', 'role') }}"
  when:
    - proxmox__manage_roles
    - proxmox_datacenter_roles | length > 0

- name: Include Proxmox Datacenter User Groups Task
  ansible.builtin.include_tasks:
    file: datacenter/user_groups.yml
  vars:
    proxmox_datacenter_user_groups: "{{ proxmox__all | selectattr('entry__type', 'eq', 'user_group') }}"
  when:
    - proxmox__manage_user_groups
    - proxmox_datacenter_user_groups | length > 0

- name: Include Proxmox Datacenter Users Task
  ansible.builtin.include_tasks:
    file: datacenter/users.yml
  vars:
    proxmox_datacenter_users: "{{ proxmox__all | selectattr('entry__type', 'eq', 'user') }}"
  when:
    - proxmox__manage_users
    - proxmox_datacenter_users | length > 0

- name: Include Proxmox Datacenter ACLs Task
  ansible.builtin.include_tasks:
    file: datacenter/acls.yml
  vars:
    proxmox_datacenter_acls: "{{ proxmox__all | selectattr('entry__type', 'eq', 'acl') }}"
  when:
    - proxmox__manage_acls
    - proxmox_datacenter_acls | length > 0