---
- name: Apply Proxmox Freenas Changes
  block:
    - name: Set Facts for Proxmox Freenas
      ansible.builtin.set_fact:
        freenas_remote_src: "{{ proxmox__purposes.freenas.params.remote_src | default(true) }}"
        freenas_delegate: "{{ inventory_hostname if freenas_remote_src else 'localhost' }}"
      register: proxmox__freenas__set_fact

    - name: Create Temp Directory for Git Repo
      ansible.builtin.tempfile:
        state: directory
      register: proxmox__freenas__temp_dir
      delegate_to: "{{ freenas_delegate }}"
    
    - name: Debug
      ansible.builtin.debug:
        msg:
          proxmox__freenas__temp_dir: "{{ proxmox__freenas__temp_dir }}"
      delegate_to: localhost

    - name: Include Git Task to Clone Freenas Repo
      ansible.builtin.include_role:
        name: aybarsm.helper.misc
        tasks_from: git.yml
      vars:
        misc__git:
          repo: https://github.com/TheGrandWazoo/freenas-proxmox
          clone: true
          dest: proxmox__freenas__temp_dir.path
      register: proxmox__freenas__git
      delegate_to: "{{ freenas_delegate }}"
      when: proxmox__freenas__temp_dir.path is defined
    
    - name: Include File Manager Role to Apply Changes
      ansible.builtin.include_role:
        name: aybarsm.helper.file_mgr        
      vars:
        file_mgr__role_enabled: true
        file_mgr__no_log: false
        file_mgr__use_only: ['host']
        file_mgr__host:
          - entry__type: patch
            src: "{{ proxmox__freenas__temp_dir.path }}/pve-manager/js/pvemanagerlib.js.patch"
            # dest: /usr/share/pve-manager/js/pvemanagerlib.js
            dest: /root/pve_freenas/pvemanagerlib.js
            backup: true
            remote_src: "{{ freenas_remote_src }}"
            entry__handlers: restart_pve_services
          - entry__type: patch
            src: "{{ proxmox__freenas__temp_dir.path }}/perl5/PVE/Storage/ZFSPlugin.pm.patch"
            dest: /root/pve_freenas/ZFSasdsadsaPlugin.pm
            # dest: /root/pve_freenas/ZFSPlugin.pm
            # dest: /usr/share/perl5/PVE/Storage/ZFSPlugin.pm
            backup: true
            remote_src: "{{ freenas_remote_src }}"
            entry__handlers: restart_pve_services
          - entry__type: patch
            src: "{{ proxmox__freenas__temp_dir.path }}/pve-docs/api-viewer/apidoc.js.patch"
            # dest: /usr/share/pve-docs/api-viewer/apidoc.js
            dest: /root/pve_freenas/apidoc.js
            backup: true
            remote_src: "{{ freenas_remote_src }}"
            entry__handlers: restart_pve_services
          - entry__type: copy
            src: "{{ proxmox__freenas__temp_dir.path }}/perl5/PVE/Storage/LunCmd/FreeNAS.pm"
            # dest: /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm
            dest: /root/pve_freenas/FreeNAS.pm
            backup: true
            remote_src: "{{ freenas_remote_src }}"
            entry__handlers: restart_pve_services
          - entry__type: handlers
            name: restart_pve_services
            condition: any
            handlers: "{{ {'name': ['pvedaemon', 'pveproxy', 'pvestatd', 'pve-ha-lrm', 'pve-ha-crm']} | 
              aybarsm.helper.to_list_of_dicts({'entry__type': 'service', 'state': 'restarted'}) }}"
      register: proxmox__freenas__patch
      when: proxmox__freenas__temp_dir.path is defined
  
  rescue:
    - name: Restate Backup Files on Error
      ansible.builtin.file:
        src: "{{ item.entry__task.backup_file }}"
        dest: "{{ item.entry__task.dest }}"
      loop: "{{ backup_files }}"
      vars:
        backup_files: "{{ file_mgr__items | selectattr('entry__task.backup_file', 'defined') }}"
      when: backup_files | length > 0
      register: proxmox__freenas__restore

  always:
    - name: Remove Temp Directory
      ansible.builtin.file:
        path: "{{ proxmox__freenas__temp_dir.path }}"
        state: absent
      delegate_to: "{{ freenas_delegate }}"
      when: proxmox__freenas__temp_dir.path is defined
        

