---
# - name: Include Package Manager Tasks
#   ansible.builtin.include_tasks:
#     file: package_manager.yml
#   when:
#     - proxmox__role_enabled
#     - proxmox__manage_repo_keys or proxmox__manage_repos or proxmox__manage_packages
#   tags: '{{"always" if proxmox__role_enabled else "never"}}'

# - name: Include Datacenter Tasks
#   ansible.builtin.include_tasks:
#     file: datacenter.yml
#   when:
#     - proxmox__role_enabled

# - name: Remove subscription check wrapper function in web UI
#   become: true
#   ansible.builtin.lineinfile:
#     path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
#     line: '        orig_cmd(); return;'
#     insertafter: '^\s+checked_command: function\(orig_cmd\) {$'
#     firstmatch: true
#     backup: true
#   when:
#     - proxmox__role_enabled
#     - proxmox__remove_subscription_warning | bool

- name: Include Freenas Tasks
  ansible.builtin.include_tasks:
    file: "{{ __proxmox__purposes.freenas.task_file }}"
  when:
    - proxmox__role_enabled
    - __proxmox__purposes.freenas is defined