---
- name: Include Proxmox QEMU tasks
  ansible.builtin.include_tasks:
    file: qemu.yml
  loop: "{{ proxmox__all | selectattr('entry__type', 'match', '^qemu_(vm|disk|nic)$') }}"
  loop_control:
    loop_var: proxmox__qemu_item
    index_var: proxmox__qemu_item_index
  when:
    - proxmox__role_enabled | default(false) | bool
    - proxmox__all | selectattr('entry__type', 'match', '^qemu_(vm|disk|nic)$') | default([]) | length > 0