- name: Include Package Manager
  ansible.builtin.include_role:
    name: aybarsm.linux.pkg_mgr
  vars:
    pkg_mgr__role_enabled: true
    pkg_mgr__manage_repo_keys: "{{ proxmox__manage_repo_keys }}"
    pkg_mgr__manage_repos: "{{ proxmox__manage_repos }}"
    pkg_mgr__manage_packages: "{{ proxmox__manage_packages }}"
    pkg_mgr__package_module: specific
    pkg_mgr__upgrade_strategy: never
    pkg_mgr__use_only: ['host']
    pkg_mgr__host: "{{ __proxmox__pkg_mgr }}"
  register: proxmox__pkg_mgr