---
- name: Include aybarsm package_manager role
  ansible.builtin.include_role:
    name: aybarsm.linux.package_manager
  vars:
    package_manager__role_enabled: "{{ proxmox__manage_repo_keys or proxmox__manage_repos or proxmox__manage_packages }}"
    package_manager__manage_repo_keys: "{{ proxmox__manage_repo_keys }}"
    package_manager__manage_repos: "{{ proxmox__manage_repos }}"
    package_manager__manage_packages: "{{ proxmox__manage_packages }}"
    package_manager__all: "{{ __proxmox__purpose_packages }}"