---
- name: Proxmox QEMU Item
  block:
    - name: "Include QEMU VM Tasks - Index: {{ proxmox_qemu_item_index }}"
      ansible.builtin.include_tasks:
        file: qemu/vm.yml
      vars:
        qemu_vm: "{{ __proxmox__module_vars | combine(proxmox__qemu_item) }}"
      when: proxmox__qemu_item.entry__type == 'qemu_vm'
    
    - name: "Include QEMU NIC Tasks - Index: {{ proxmox_qemu_item_index }}"
      ansible.builtin.include_tasks:
        file: qemu/nic.yml
      vars:
        qemu_nic: "{{ __proxmox__module_vars | combine(proxmox__qemu_item) }}"
      when: proxmox__qemu_item.entry__type == 'qemu_nic'
    
    - name: "Include QEMU DISK Tasks - Index: {{ proxmox_qemu_item_index }}"
      ansible.builtin.include_tasks:
        file: qemu/disk.yml
      vars:
        qemu_disk: "{{ __proxmox__module_vars | combine(proxmox__qemu_item) }}"
      when: proxmox__qemu_item.entry__type == 'qemu_disk'
