---
- name: Set main fact for main proxmox cluster configuration
  ansible.builtin.set_fact:
    __proxmox__cluster_configs: "{{ (__proxmox__cluster_configs | default([]) + cluster_config) | sort(attribute='name,host') }}"
  vars:
    cluster_inventory: "{{ lookup('ansible.builtin.inventory_hostnames', item.target) }}"
    cluster_query: "{{ __proxmox__cluster_query | replace('__MEMBERS__', ('[`' + (cluster_inventory | replace(',', '`,`')) + '`]')) }}"
    cluster_node_config: "{{ dict(hostvars) | community.general.json_query(cluster_query) | sort(attribute='host') }}"
    cluster_default_init: "{{ cluster_node_config | map(attribute='host') | first }}"
    cluster_config: "{{ cluster_node_config | map('combine', ({'init': cluster_default_init} | combine(__proxmox__default_cluster_config, item))) }}"
  loop: "{{ proxmox__clusters }}"
  delegate_to: localhost
  run_once: true
  when:
    - proxmox__clusters is defined
    - proxmox__clusters | length > 0
    - __proxmox__cluster_query is defined

- name: Set facts for proxmox cluster configuration
  ansible.builtin.set_fact:
    __proxmox__cluster: "{{ {'members': cluster_members} | combine(cluster_play) if cluster_eligible else None }}"
    __proxmox__cluster_eligible: "{{ cluster_eligible }}"

    package_manager__role_enabled: "{{ use_package_manager if use_package_manager else omit }}"
    package_manager__manage_repo_keys: "{{ proxmox__manage_repo_keys if proxmox__manage_repo_keys else omit }}"
    package_manager__manage_repos: "{{ proxmox__manage_repos if proxmox__manage_repos else omit }}"
    package_manager__manage_packages: "{{ proxmox__manage_packages if proxmox__manage_packages else omit }}"
    package_manager__host: "{{ node_repo_keys + node_repos + node_packages + (package_manager__host | default([])) if use_package_manager else omit }}"

    grub__role_enabled: "{{ proxmox__manage_grub if proxmox__manage_grub else omit }}"
    grub__change_strategy: "{{ __proxmox__grub_change_strategy if proxmox__manage_grub else omit }}"

    network__role_enabled: "{{ use_network if use_network else omit }}"
    network__manage_hostname: "{{ proxmox__manage_hostname if proxmox__manage_hostname else omit }}"
    network__manage_hosts: "{{ proxmox__manage_hosts if proxmox__manage_hosts else omit }}"
    network__manage_iptables: "{{ proxmox__manage_iptables if proxmox__manage_iptables else omit }}"
    network__hosts_auto_discovery: "{{ False if proxmox__manage_hosts else omit }}"
    network__hostname: "{{ proxmox__hostname + '.' + proxmox__domain if proxmox__manage_hostname else omit }}"
    network__host: "{{ node_hosts + (network__host | default([])) if cluster_eligible and proxmox__manage_hosts else omit }}"

    auth__role_enabled: "{{ use_auth if use_auth else omit }}"
    auth__manage_users: "{{ proxmox__manage_root_access if cluster_eligible and proxmox__manage_root_access else omit }}"
    auth__manage_authorized_keys: "{{ proxmox__manage_root_access if cluster_eligible and proxmox__manage_root_access else omit }}"
    auth__manage_sshd_config: "{{ proxmox__manage_sshd_config if cluster_eligible and proxmox__manage_sshd_config else omit }}"
    auth__manage_ssh_config: "{{ proxmox__manage_ssh_config if cluster_eligible and proxmox__manage_ssh_config else omit }}"
    auth__host: "{{ node_auth + (auth__host | default([])) if cluster_eligible and use_auth else omit }}"
  vars:
    cluster_play: "{{ __proxmox__cluster_configs | selectattr('host', 'eq', inventory_hostname) | first | default(None) }}"
    cluster_members: "{{ __proxmox__cluster_configs |
      selectattr('name', 'eq', cluster_play.name) |
      rejectattr('host', 'eq', inventory_hostname) |
      aybarsm.helper.only_with(['host', 'fqdn', 'hostname', 'links']) if cluster_play else None }}"
    cluster_required: "{{ [inventory_hostname] + (cluster_members | map(attribute='host') | list) if cluster_play else None }}"
    cluster_eligible: "{{ (ansible_play_batch | intersect(cluster_required) | length) == (cluster_required | length) if cluster_play else False }}"

    use_package_manager: "{{ proxmox__manage_repo_keys or proxmox__manage_repos or proxmox__manage_packages }}"
    use_network: "{{ proxmox__manage_hostname or proxmox__manage_hosts or proxmox__manage_iptables }}"
    use_auth: "{{ proxmox__manage_root_access or proxmox__manage_sshd_config or proxmox__manage_ssh_config }}"

    node_repo_keys: "{{ __proxmox__purpose_packages | selectattr('type', 'eq', 'repo_key') if proxmox__manage_repo_keys else [] }}"
    node_repos: "{{ __proxmox__purpose_packages | selectattr('type', 'eq', 'repo') if proxmox__manage_repos else [] }}"
    node_packages: "{{ __proxmox__purpose_packages | selectattr('type', 'eq', 'package') + [{
      'type': 'package',
      'name': 'os-prober',
      'state': 'absent',
      'update_cache': true
      }] if proxmox__manage_packages else [] }}"

    cluster_hosts: "{{ [cluster_play | aybarsm.helper.only_with(['hostname', 'fqdn', 'links'])] + cluster_members if cluster_eligible else None }}"
    node_hosts: "{{ {
      'ip': (cluster_hosts | map(attribute='links') | map('first')),
      'hostname': (cluster_hosts | map(attribute='hostname')),
      'fqdn': (cluster_hosts | map(attribute='fqdn'))
      } | aybarsm.helper.to_list_of_dicts({'type': 'host'}) if cluster_eligible and proxmox__manage_hosts else [] }}"

    node_auth_all: "{{ (auth__host | default([])) + (auth__group | default([])) + (auth__default | default([])) if cluster_eligible else [] }}"

    node_root_default: "{{ node_auth_all | aybarsm.helper.selectattr(__proxmox__root_user_selector) | first | default({}) if cluster_eligible else {} }}"
    node_root_modification:
      ssh_key_comment: "{{ node_root_default.ssh_key_comment | default('root@' + (cluster_play.hostname if cluster_eligible else inventory_hostname_short)) }}"
      distribute_ssh_key: "{{ cluster_required if cluster_eligible else [] }}"
    node_root_user: "{{ node_root_default | combine(__proxmox__root_user, node_root_modification) }}"

    node_ssh_hosts: "{{ cluster_members | map(attribute='links') | map('join', ' ') | join(' ') if cluster_eligible else '' }}"
    node_ssh_config: "{{ __proxmox__ssh_config | combine({'value': node_ssh_hosts}) if cluster_eligible else [] }}"

    node_sshd_matches: "{{ cluster_members | map(attribute='links') | map('join', ',') | join(',') if cluster_eligible else '' }}"
    node_sshd_config: "{{ __proxmox__sshd_config | combine({'value': node_sshd_matches}) if cluster_eligible else [] }}"

    node_auth: "{{ ([node_root_user] if cluster_eligible and proxmox__manage_root_access else []) +
      ([node_ssh_config] if cluster_eligible and proxmox__manage_ssh_config else []) +
      ([node_sshd_config] if cluster_eligible and proxmox__manage_sshd_config else []) }}"
  when:
    - __proxmox__cluster_configs | length > 0
