---
- name: Import aybarsm.helper.file_mgr role for Proxmox SSL Config
  ansible.builtin.import_role:
    name: aybarsm.helper.file_mgr
  vars:
    file_mgr__role_enabled: true
    file_mgr__use_only: ['host']
    file_mgr__host:
      - entry__type: copy
        entry__keep: "{{ (proxmox__ssl_certificate | default(undef(), true)) is defined }}"
        content: "{{ lookup('file', proxmox__ssl_certificate) if (proxmox__ssl_certificate | default(undef(), true)) is defined else omit }}"
        dest: /etc/pve/local/pve-ssl.pem
        mode: '0640'
        owner: root
        group: 'www-data'
        entry__handlers:
          - entry__type: service
            name: pveproxy
            state: restarted
      - entry__type: copy
        entry__keep: "{{ (proxmox__ssl_key | default(undef(), true)) is defined }}"
        content: "{{ lookup('file', proxmox__ssl_key) if (proxmox__ssl_key | default(undef(), true)) is defined else omit }}"
        dest: /etc/pve/local/pve-ssl.key
        mode: '0640'
        owner: root
        group: 'www-data'
        entry__handlers:
          - entry__type: service
            name: pveproxy
            state: restarted