---
- name: Apply command(s) for linux_grub changes
  become: true
  ansible.builtin.command:
    argv: "{{ item.argv | default(omit) }}"
    chdir: "{{ item.chdir | default(omit) }}"
    cmd: "{{ item.cmd }}"
    creates: "{{ item.creates | default(omit) }}"
    expand_argument_vars: "{{ item.expand_argument_vars | default(omit) }}"
    free_form: "{{ item.free_form | default(omit) }}"
    removes: "{{ item.removes | default(omit) }}"
    stdin: "{{ item.stdin | default(omit) }}"
    stdin_add_newline: "{{ item.stdin_add_newline | default(omit) }}"
    strip_empty_ends: "{{ item.strip_empty_ends | default(omit) }}"
  loop: "{{ linux_grub_change | selectattr('cmd', 'defined') }}"
  register: linux_grub_apply_changes_command
  when:
    - linux_grub_change | type_debug == 'list'
    - linux_grub_change | selectattr('cmd', 'defined') | length > 0
