---
- name: Apply grub changes via command module
  become: true
  ansible.builtin.command:
    chdir: "{{ item.chdir | default(omit) }}"
    cmd: "{{ item.cmd }}"
    creates: "{{ item.creates | default(omit) }}"
    removes: "{{ item.removes | default(omit) }}"
    stdin: "{{ item.stdin | default(omit) }}"
    stdin_add_newline: "{{ item.stdin_add_newline | default(omit) }}"
    strip_empty_ends: "{{ item.strip_empty_ends | default(omit) }}"
  loop: "{{ grub__change_strategy.cmds | default([grub__change_strategy]) }}"
  changed_when: true
  register: grub__apply_changes_command
  listen: "grub__apply_changes"
  when:
    - grub__change_strategy.module is defined
    - grub__change_strategy.module == 'command'
