---
- name: Apply grub changes via command module
  become: true
  ansible.builtin.command:
    chdir: "{{ grub__change_strategy.chdir | default(omit) }}"
    cmd: "{{ grub__change_strategy.cmd }}"
    creates: "{{ grub__change_strategy.creates | default(omit) }}"
    removes: "{{ grub__change_strategy.removes | default(omit) }}"
    stdin: "{{ grub__change_strategy.stdin | default(omit) }}"
    stdin_add_newline: "{{ grub__change_strategy.stdin_add_newline | default(omit) }}"
    strip_empty_ends: "{{ grub__change_strategy.strip_empty_ends | default(omit) }}"
  changed_when: true
  register: grub__apply_changes_command
  listen: "grub__apply_changes"
  when:
    - grub__change_strategy.module is defined
    - grub__change_strategy.module == 'command'
