---
- name: Set fact for ssh key distribution to authorized keys, if any
  ansible.builtin.set_fact:
    auth__authorized_keys_all: "{{ (auth__authorized_keys_all | default([])) + ssh_keys_distribute }}"
  vars:
    ssh_keys_distribute: "{{ dict(hostvars) |
      aybarsm.helper.only_with(ansible_play_batch) |
      community.general.json_query(__auth__key_distribute_query) | default([]) }}"
  register: auth__users__ssh_key_distribution
  when:
    - auth__users_apply.results is defined
    - auth__users_apply.results | length > 0
    - ssh_keys_distribute | length > 0

- name: Retrieve passwd database in check mode for authorized keys
  become: true
  ansible.builtin.getent:
    database: passwd
  register: auth__authorized_keys_test_user_existence
  when:
    - auth__authorized_keys_all | length > 0
    - ansible_check_mode

- name: Apply authorized keys configuration
  become: true
  ansible.posix.authorized_key:
    comment: "{{ item.comment | default(omit, true) }}"
    exclusive: "{{ item.exclusive | default(omit, true) }}"
    follow: "{{ item.follow | default(omit, true) }}"
    key: "{{ item.key }}"
    key_options: "{{ item.key_options | default(omit, true) }}"
    manage_dir: "{{ item.manage_dir | default(omit, true) }}"
    path: "{{ item.path | default(omit, true) }}"
    state: "{{ item.state | default(omit, true) }}"
    user: "{{ item.user }}"
    validate_certs: "{{ item.validate_certs | default(omit, true) }}"
  loop: "{{ auth__authorized_keys_all }}"
  no_log: "{{ auth__no_log | default(true, true) | bool }}"
  register: auth__authorized_keys_apply
  when:
    - auth__authorized_keys_all | length > 0
    - not ansible_check_mode | bool or (ansible_check_mode and (item.user in ansible_facts['getent_passwd'] or item.path is defined))
