---
- name: Cleanup unexpected ssh DAEMON config files
  block:
    - name: Find unexpected ssh DAEMON config files
      become: true
      ansible.builtin.find:
        paths: "{{ auth__sshd_config_dir }}"
        patterns: "(?!{{ auth__sshd_config_file | basename }})"
        use_regex: true
        hidden: true
        recurse: true
        file_type: any
      register: auth__sshd_config_find_cleanup_files

    - name: Remove unexpected ssh DAEMON config files
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ auth__sshd_config_find_cleanup_files.files | map(attribute='path') }}"
      register: auth__sshd_config_cleanup_files
      notify: "auth__ssh_apply_changes"
      when: auth__sshd_config_find_cleanup_files.files | default([]) | length > 0
  when: auth__sshd_config_cleanup | default(false) | bool

- name: Apply ssh DAEMON configuration
  become: true
  ansible.builtin.template:
    src: "{{ auth__sshd_config_template }}"
    dest: "{{ auth__sshd_config_file }}"
    backup: "{{ auth__sshd_config_backup | default(omit) | bool }}"
    validate: "{{ auth__sshd_validate | default(omit) }}"
    mode: "{{ auth__sshd_config_file_module.mode | default(omit, true) }}"
    owner: "{{ auth__sshd_config_file_module.owner | default(omit, true) }}"
    group: "{{ auth__sshd_config_file_module.group | default(omit, true) }}"
  register: auth__sshd_config_apply
  notify: "auth__ssh_apply_changes"
  when: auth__sshd_config_all | default([]) | length > 0

- name: Cleanup unexpected ssh CLIENT config files
  block:
    - name: Find unexpected ssh CLIENT config files
      become: true
      ansible.builtin.find:
        paths: "{{ auth__ssh_config_dir }}"
        patterns: "(?!{{ auth__ssh_config_file | basename }})"
        use_regex: true
        hidden: true
        recurse: true
        file_type: any
      register: auth__ssh_config_find_cleanup_files

    - name: Remove unexpected ssh CLIENT config files
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ auth__ssh_config_find_cleanup_files.files | map(attribute='path') }}"
      register: auth__ssh_config_cleanup_files
      notify: "auth__ssh_apply_changes"
      when: auth__ssh_config_find_cleanup_files.files | default([]) | length > 0
  when: auth__ssh_config_cleanup | default(false) | bool

- name: Apply ssh CLIENT configuration
  become: true
  ansible.builtin.template:
    src: "{{ auth__ssh_config_template }}"
    dest: "{{ auth__ssh_config_file }}"
    backup: "{{ auth__ssh_config_backup | default(omit) | bool }}"
    mode: "{{ auth__ssh_config_file_module.mode | default(omit, true) }}"
    owner: "{{ auth__ssh_config_file_module.owner | default(omit, true) }}"
    group: "{{ auth__ssh_config_file_module.group | default(omit, true) }}"
  register: auth__ssh_config_apply
  notify: "auth__ssh_apply_changes"
  when: auth__ssh_config_all | default([]) | length > 0

- name: Apply ssh client configuration via community.general.ssh_config module
  become: true
  community.general.ssh_config:
    add_keys_to_agent: "{{ item.add_keys_to_agent | default(omit) | bool }}"
    controlmaster: "{{ item.controlmaster | default(omit) }}"
    controlpath: "{{ item.controlpath | default(omit) }}"
    controlpersist: "{{ item.controlpersist | default(omit) }}"
    forward_agent: "{{ item.forward_agent | default(omit) | bool }}"
    group: "{{ item.group | default(omit) }}"
    host: "{{ item.host }}"
    host_key_algorithms: "{{ item.host_key_algorithms | default(omit) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    identities_only: "{{ item.identities_only | default(omit) | bool }}"
    identity_file: "{{ item.identity_file | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proxycommand: "{{ item.proxycommand | default(omit) }}"
    proxyjump: "{{ item.proxyjump | default(omit) }}"
    remote_user: "{{ item.remote_user | default(omit) }}"
    ssh_config_file: "{{ item.ssh_config_file | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    strict_host_key_checking: "{{ item.strict_host_key_checking | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    user_known_hosts_file: "{{ item.user_known_hosts_file | default(omit) }}"
  loop: "{{ auth__ssh_config_module_all }}"
  register: auth__ssh_config_module_apply
  notify: "auth__ssh_apply_changes"
  when: auth__ssh_config_module_all | default([]) | length > 0

- name: Run smart sshd configuration changes
  ansible.builtin.command:
    cmd: /usr/bin/true
  changed_when: true
  notify: "auth__ssh_apply_changes"
  when:
    - auth__sshd_validate is defined
    - auth__sshd_validate
    - auth__sshd_config_apply is not change
    - auth__ssh_config_apply is not change
    - auth__ssh_changes_strategy.smart | default(false) | bool

- name: Effect ssh changes
  ansible.builtin.meta: 'flush_handlers'
  when:
    - auth__ssh_changes_strategy.module is defined
    - auth__ssh_changes_strategy.immediate | default(false) | bool
