---
- name: Apply sudoers configuration file
  become: true
  ansible.builtin.template:
    src: "{{ auth__sudoers_template }}"
    dest: "{{ auth__sudoers_file }}"
    validate: "{{  auth__sudoers_validate | default(omit) }}"
  register: auth__sudoers_file_apply
  when:
    - auth__sudoers_file_all | type_debug == 'list'
    - auth__sudoers_file_all | length > 0

- name: Apply sudoers configuration via community.general.sudoers module
  become: true
  community.general.sudoers:
    commands: "{{ item.commands | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    name: "{{ item.name }}"
    noexec: "{{ item.noexec | default(omit) | bool }}"
    nopassword: "{{ item.nopassword | default(omit) | bool }}"
    runas: "{{ item.runas | default(omit) }}"
    setenv: "{{ item.setenv | default(omit) | bool }}"
    state: "{{ item.state | default(omit) }}"
    sudoers_path: "{{ item.sudoers_path | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    validation: "{{ item.validation | default(omit) }}"
  loop: "{{ auth__sudoers_module_all }}"
  register: auth__sudoers_module_apply
  when:
    - auth__sudoers_module_all | type_debug == 'list'
    - auth__sudoers_module_all | length > 0
  