---
- name: Apply command(s) for network_interfaces_ changes
  become: true
  ansible.builtin.command:
    chdir: "{{ item.chdir | default(omit) }}"
    cmd: "{{ item.cmd }}"
    creates: "{{ item.creates | default(omit) }}"
    removes: "{{ item.removes | default(omit) }}"
    stdin: "{{ item.stdin | default(omit) }}"
    stdin_add_newline: "{{ item.stdin_add_newline | default(omit) }}"
    strip_empty_ends: "{{ item.strip_empty_ends | default(omit) }}"
  changed_when: true
  loop: "{{ network_interfaces__change | selectattr('cmd', 'defined') }}"
  register: network_interfaces__apply_changes_command
  listen: "network_interfaces__apply_changes_by_command"
  when:
    - network_interfaces__change_strategy | default('') == 'command'
    - network_interfaces__change | type_debug == 'list'
    - network_interfaces__change | selectattr('cmd', 'defined') | length > 0

- name: Effect service(s) for network_interfaces_ changes
  become: true
  ansible.builtin.service:
    arguments: "{{ item.arguments | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    name: "{{ item.name }}"
    pattern: "{{ item.pattern | default(omit) }}"
    runlevel: "{{ item.runlevel | default(omit) }}"
    sleep: "{{ item.sleep | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    use: "{{ item.use | default(omit) }}"
  loop: "{{ network_interfaces__change | selectattr('name', 'defined') }}"
  register: network_interfaces__apply_changes_service
  listen: "network_interfaces__apply_changes_by_service"
  when:
    - network_interfaces__change_strategy | default('') == 'service'
    - network_interfaces__change | type_debug == 'list'
    - network_interfaces__change | selectattr('name', 'defined') | length > 0
