
__hosts__auto_discovered: >-
  {%- if (hosts__auto_discovery | default(false) | bool) and hosts__auto_discovery_inventories is defined and hosts__auto_discovery_inventories | length > 0 -%}
  {%- set inventory_lookup = lookup('ansible.builtin.inventory_hostnames', hosts__auto_discovery_inventories) -%}
  {%-   if inventory_lookup | length > 0 -%}
  {%-     set inventory_hosts = inventory_lookup | split(',') -%}
  {%-     set discovered_hosts = dict(hostvars) | aybarsm.helper.only_with(inventory_hosts) | dict2items | selectattr('value.ansible_host', 'defined') -%}
  {%-     set ips = discovered_hosts | map(attribute='value.ansible_host') -%}
  {%-     set hostnames = discovered_hosts | map(attribute='value.inventory_hostname_short') -%}
  {%-     set fqdns = discovered_hosts | map(attribute='value.inventory_hostname') -%}
  {%-     set auto_discovered = {'ip': ips, 'hostname': hostnames, 'fqdn': fqdns} | aybarsm.helper.to_list_of_dicts -%}
  {%-   endif -%}
  {%- else -%}
  {%- set auto_discovered = [] -%}
  {%- endif -%}
  {{ auto_discovered }}

hosts__all: "{{ (hosts__host + hosts__group + hosts__default + __hosts__auto_discovered) |
  aybarsm.helper.replace_aliases({'fqdn': ['hostname']}) |
  aybarsm.helper.selectattr([{'when': [['ip', 'defined'], ['hostname', 'defined'], ['fqdn', 'defined']]}]) |
  aybarsm.helper.unique_recursive(['ip', 'hostname', 'fqdn']) | default([]) }}"

hosts__all_ipv4: "{{ hosts__all | selectattr('ip', 'ansible.utils.ipv4') }}"
hosts__all_ipv6: "{{ hosts__all | selectattr('ip', 'ansible.utils.ipv6') }}"