---
- name: Deploy network hosts file configuration
  become: true
  ansible.builtin.template:
    src: "{{ network__hosts_template }}"
    dest: "{{ network__hosts_file }}"
    backup: "{{ network__hosts_backup | default(omit) | bool }}"
  when: (network__hosts_all_ipv4 | default([]) | length > 0) or (network__hosts_all_ipv6 | default([]) | length > 0)
  register: network__hosts_deploy
