---
- name: Include iptables IPv4 cleanup tasks
  ansible.builtin.include_tasks: iptables_cleanup.yml
  vars:
    iptables_cleanup_ip_ver: ipv4
    iptables_cleanup_state_file: "{{ network__iptables_cleanup_v4_state_file }}"
    iptables_cleanup_regex: "{{ network__iptables_cleanup_v4_cleanup_regex }}"
  when: network__iptables_cleanup_v4 | bool and network__iptables_cleanup_v4_cleanup_regex | length > 0

- name: Include iptables IPv6 cleanup tasks
  ansible.builtin.include_tasks: iptables_cleanup.yml
  vars:
    iptables_cleanup_ip_ver: ipv6
    iptables_cleanup_state_file: "{{ network__iptables_cleanup_v6_state_file }}"
    iptables_cleanup_regex: "{{ network__iptables_cleanup_v6_cleanup_regex }}"
  when: network__iptables_cleanup_v6 | bool and network__iptables_cleanup_v6_cleanup_regex | length > 0

- name: Deploy iptables configuration
  become: true
  ansible.builtin.iptables:
    action: "{{ item.action | default(omit) }}"
    chain: "{{ item.chain | default(omit) }}"
    chain_management: "{{ item.chain_management | default(omit) }}"
    comment: "{{ rule_comment | default(omit, true) }}"
    ctstate: "{{ item.ctstate | default(omit) }}"
    destination: "{{ item.destination | default(omit) }}"
    destination_port: "{{ item.destination_port | default(omit) }}"
    destination_ports: "{{ item.destination_ports | default(omit) }}"
    dst_range: "{{ item.dst_range | default(omit) }}"
    flush: "{{ item.flush | default(omit) }}"
    fragment: "{{ item.fragment | default(omit) }}"
    gateway: "{{ item.gateway | default(omit) }}"
    gid_owner: "{{ item.gid_owner | default(omit) }}"
    go†o: "{{ item.goto | default(omit) }}"
    icmp_type: "{{ item.icmp_type | default(omit) }}"
    in_interface: "{{ item.in_interface | default(omit) }}"
    ip_version: "{{ item.ip_version | default(omit) }}"
    jump: "{{ item.jump | default(omit) }}"
    limit: "{{ item.limit | default(omit) }}"
    limit_burst: "{{ item.limit_burst | default(omit) }}"
    log_level: "{{ item.log_level | default(omit) }}"
    log_prefix: "{{ item.log_prefix | default(omit) }}"
    match: "{{ item.match | default(omit) }}"
    match_set: "{{ item.match_set | default(omit) }}"
    match_set_flags: "{{ item.match_set_flags | default(omit) }}"
    numeric: "{{ item.numeric | default(omit) }}"
    out_interface: "{{ item.out_interface | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    protocol: "{{ item.protocol | default(omit) }}"
    reject_with: "{{ item.reject_with | default(omit) }}"
    rule_num: "{{ item.rule_num | default(omit) }}"
    set_counters: "{{ item.set_counters | default(omit) }}"
    set_dscp_mark: "{{ item.set_dscp_mark | default(omit) }}"
    set_dscp_mark_class: "{{ item.set_dscp_mark_class | default(omit) }}"
    source: "{{ item.source | default(omit) }}"
    source_port: "{{ item.source_port | default(omit) }}"
    src_range: "{{ item.src_range | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    syn: "{{ item.syn | default(omit) }}"
    table: "{{ item.table | default(omit) }}"
    tcp_flags: "{{ item.tcp_flags | default(omit) }}"
    to_destination: "{{ item.to_destination | default(omit) }}"
    to_ports: "{{ item.to_ports | default(omit) }}"
    to_source: "{{ item.to_source | default(omit) }}"
    uid_owner: "{{ item.uid_owner | default(omit) }}"
    wait: "{{ item.wait | default(omit) }}"
  vars:
    rule_comment: "{{ [(network__iptables_comment_prefix | default('')), (item.comment | default('')), (network__iptables_comment_suffix | default(''))] |
      join(' ') | trim }}"
  loop: "{{ network__iptables_all }}"
  register: network__iptables_deploy
  when: network__iptables_all | default([]) | length > 0

#TODO: Iptables cleanup regex
