---
- name: Deploy posix sysctl configuration
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    ignoreerrors: "{{ item.ignoreerrors | default(omit) }}"
    reload: "{{ item.reload | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    sysctl_file: "{{ item.sysctl_file | default(omit) }}"
    sysctl_set: "{{ item.sysctl_set | default(omit) }}"
  loop: "{{ network__sysctl_all }}"
  register: network__sysctl_deploy
  when:
    - network__sysctl_all | type_debug == 'list'
    - network__sysctl_all | length > 0
