__package_manager__clean_upgrade_modes: "{{ ['clean_'] | product(__package_manager__upgrade_modes) | map('join') }}"

package_manager__packages_all: "{{ package_manager__all |
  aybarsm.helper.selectattr(__package_manager__config.packages.selectattr) |
  aybarsm.helper.replace_aliases(__package_manager__config.packages.replace_aliases) |
  aybarsm.helper.splitattr(__package_manager__config.packages.splitattr) |
  aybarsm.helper.unique_recursive(attribute=__package_manager__config.packages.uniques) |
  aybarsm.helper.joinattr(__package_manager__config.packages.joinattr) |
  default([]) }}"

package_manager__repo_keys_all: "{{ package_manager__all |
  aybarsm.helper.selectattr(__package_manager__config.repo_keys.selectattr) |
  aybarsm.helper.unique_recursive(__package_manager__config.repo_keys.uniques) |
  default([]) }}"

package_manager__repos_all: "{{ package_manager__all |
  aybarsm.helper.selectattr(__package_manager__config.repos.selectattr) |
  aybarsm.helper.unique_recursive(__package_manager__config.repos.uniques) |
  default([]) }}"

package_manager__repo_lists_all: "{{ package_manager__all |
  aybarsm.helper.selectattr(__package_manager__config.repo_lists.selectattr) |
  aybarsm.helper.unique_recursive(__package_manager__config.repo_lists.uniques) |
  default([]) }}"