linux_package_manager_packages_all: "{{ linux_package_manager_all |
  aybarsm.helper.selectattr(__linux_package_manager_package_config.selectattr) |
  aybarsm.helper.setattr(__linux_package_manager_package_config.setattr) |
  aybarsm.helper.splitattr(__linux_package_manager_package_config.splitattr) |
  aybarsm.helper.unique_recursive(__linux_package_manager_package_config.uniques) |
  aybarsm.helper.joinattr(__linux_package_manager_package_config.joinattr) | default([]) }}"

linux_package_manager_repos_all: "{{ linux_package_manager_all |
  aybarsm.helper.selectattr(__linux_package_manager_repo_config.selectattr) |
  aybarsm.helper.unique_recursive(__linux_package_manager_repo_config.uniques) |
  aybarsm.helper.setattr(__linux_package_manager_repo_config.setattr) | default([]) }}"

linux_package_manager_repo_keys_all: "{{ linux_package_manager_all |
  aybarsm.helper.selectattr(__linux_package_manager_repo_key_config.selectattr) |
  aybarsm.helper.unique_recursive(__linux_package_manager_repo_key_config.uniques) |
  aybarsm.helper.setattr(__linux_package_manager_repo_key_config.setattr) | default([]) }}"
