__package_manager__upgrade_modes: ['full', 'safe', 'yes', 'dist']

package_manager__repo_list_dir: /etc/apt/sources.list.d
package_manager__repo_list_patterns: [".*\\.list$"]
package_manager__upgrade_dpkg_options: ''

__package_manager__config:
  packages:
    selectattr:
    - when:
        - ['type', 'defined']
        - ['type', 'equalto', 'package']
    - when: "{{ ['name', 'package', 'pkg'] | product(['defined']) | list }}"
      logic: or
    replace_aliases:
      name: ['package', 'pkg']
    splitattr:
      - srcAttr: name
        dstAttr: version
        search: '='
        overwrite: true
    uniques: ['name']
    joinattr:
      - leftAttr: name
        rightAttr: version
        join: '='
        overwrite: true
        deleteSrcAttrs: true
  repo_keys:
    selectattr:
    - when:
        - ['type', 'defined']
        - ['type', 'equalto', 'repo_key']
    - when: "{{ ['keyserver', 'url', 'id', 'file', 'data'] | product(['defined']) | list }}"
      logic: or
    uniques: ['keyserver', 'url', 'id', 'file', 'data']
  repos:
    selectattr:
    - when:
        - ['type', 'defined']
        - ['type', 'equalto', 'repo']
        - ['repo', 'defined']
    uniques: ['repo']
  repo_lists:
    selectattr:
    - when:
        - ['type', 'defined']
        - ['type', 'equalto', 'repo_list']
        - ['dest', 'defined']
        - ['src', 'defined']
        - ['source_module', 'defined']
        - ['source_module', 'in', ['copy', 'template']]
    uniques: ['dest']
