# FIXME: This is a test file. It should be removed after the role is tested.

package_manager__repo_list_templates:
  - type: default
    dest: /etc/apt/sources.list
    src: etc/apt/default.sources.list.j2

package_manager__repo_list_dir: /etc/apt/sources.list.d
package_manager__repo_list_use_regex: true
package_manager__repo_list_patterns: [".*\\.list$"]

package_manager__upgrade_dpkg_options: ''
package_manager__upgrade_update_repo_cache: true

__package_manager__upgrade_modes: ['full', 'safe', 'yes', 'dist']
__package_manager__clean_upgrade_modes: "{{ ['clean_'] | product(__package_manager__upgrade_modes) | map('join') }}"

__package_manager__uniques_package: ['name', 'package', 'pkg']
__package_manager__uniques_repo: ['repo']
__package_manager__uniques_repo_key: ['keyserver', 'url', 'id', 'data', 'file']

__package_manager__package_config:
  uniques: "{{ __package_manager__uniques_package }}"
  selectattr:
    - when:
        - ['type', 'defined']
        - ['type', 'equalto', 'package']
    - when: "{{ __package_manager__uniques_package | product(['defined']) | list }}"
      logic: or
  replace_keys:
    - before: package
      after: name
    - before: pkg
      after: name
  setattr:
    - attribute: state
      value: present
      when:
        - ['state', 'undefined']
  splitattr:
    - srcAttr: name
      dstAttr: version
      search: '='
      overwrite: true
  joinattr:
    - leftAttr: name
      rightAttr: version
      join: '='
      overwrite: true
      deleteSrcAttrs: true

__package_manager__repo_config:
  uniques: "{{ __package_manager__uniques_repo }}"
  selectattr:
    - when:
      - ['type', 'defined']
      - ['type', 'equalto', 'repo']
    - when: "{{ __package_manager__uniques_repo | product(['defined']) }}"
      logic: or
  setattr:
    - attribute: state
      value: present
      overwrite: false

__package_manager__repo_key_config:
  uniques: "{{ __package_manager__uniques_repo_key }}"
  selectattr:
    - when:
      - ['type', 'defined']
      - ['type', 'equalto', 'repo_key']
    - when: "{{ __package_manager__uniques_repo_key | product(['defined']) }}"
      logic: or
  setattr:
    - attribute: state
      value: present
      overwrite: false
