---
linux_manage_systemd_network: false
# Ensures system manager is systemd - ansible_service_mgr == "systemd"
linux_systemd_network_ensure_service_manager: true

linux_systemd_network_apply_changes: false
linux_systemd_network_responsible_services:
  - systemd
  - systemd-networkd

linux_systemd_network_backup_units: true
linux_systemd_network_cleanup_units: false
linux_systemd_network_cleanup_patterns_use_regex: true

# Consult: https://manpages.debian.org/bookworm/systemd/systemd.net-naming-scheme.7.en.html
linux_systemd_network_naming_scheme: "v252"
linux_systemd_network_naming_scheme_apply_kernel: false

linux_systemd_network_unit_dir: /etc/systemd/network
linux_systemd_network_unit_template: systemd_network_unit.j2

linux_systemd_network_units_default: []
linux_systemd_network_units_group: []
linux_systemd_network_units_host: []
linux_systemd_network_units_all: "{{ (linux_systemd_network_units_host + linux_systemd_network_units_group + linux_systemd_network_units_default) |
  selectattr('name', 'defined') | selectattr('name', 'search', '\\.(network|link|netdev)$') |
  selectattr('config', 'defined') | unique(attribute='name') }}"

__linux_systemd_network_unit_names: "{{ linux_systemd_network_units_all | map(attribute='name') }}"
__linux_systemd_network_unit_regex:
  - "^({{ __linux_systemd_network_unit_names | select('match', '.*\\.link$') | map('replace', '.link', '') | join('|') }})\\.link$"
  - "^({{ __linux_systemd_network_unit_names | select('match', '.*\\.netdev$') | map('replace', '.netdev', '') | join('|') }})\\.netdev$"
  - "^({{ __linux_systemd_network_unit_names | select('match', '.*\\.network$') | map('replace', '.network', '') | join('|') }})\\.network$"
# Escape backup files:
  - "^.*\\.\\d+\\.\\d{4}-\\d{2}-\\d{2}@\\d{2}:\\d{2}:\\d{2}~$"
__linux_systemd_network_cleanup_pattern: "(?!{{ __linux_systemd_network_unit_regex | join('|') }})"

linux_systemd_network_cleanup_patterns: ["(?!{{ __linux_systemd_network_unit_regex | join('|') }})"]
