---
- name: Deploy network interfaces configuration
  become: true
  ansible.builtin.template:
    src: "{{ linux_network_interfaces_template }}"
    dest: "{{ linux_network_interfaces_file_destination }}"
    backup: "{{ linux_network_interfaces_backup | default(omit) | bool }}"
    mode: "0644"
  when:
    - linux_network_interfaces_ifaces_all | type_debug == 'list'
    - linux_network_interfaces_ifaces_all | length > 0
  register: linux_network_interfaces_deploy_file
  notify: linux_network_interfaces_apply_changes
