---
- name: Deploy network interfaces configuration
  become: true
  ansible.builtin.template:
    src: "{{ network_interfaces__template }}"
    dest: "{{ network_interfaces__file_destination }}"
    backup: "{{ network_interfaces__backup | default(omit) | bool }}"
    mode: "0644"
  when:
    - network_interfaces__all | type_debug == 'list'
    - network_interfaces__all | length > 0
  register: network_interfaces__deploy_file
  notify:
    - network_interfaces__apply_changes_by_command
    - network_interfaces__apply_changes_by_service
