---
auth__all: "{{ auth__host + auth__group + auth__default }}"

__auth__config:
  authorized_keys:
    selectattr:
      - when:
          - ['type', 'defined']
          - ['type', 'equalto', 'authorized_key']
          - ['user', 'defined']
          - ['key', 'defined']
  groups:
    selectattr:
      - when:
          - ['type', 'defined']
          - ['type', 'equalto', 'group']
      - when: "{{ __ansible__config.modules.ansible_builtin_group.uniques | product(['defined']) | list }}"
        logic: or
  users:
    selectattr:
      - when:
          - ['type', 'defined']
          - ['type', 'equalto', 'user']
      - when: "{{ __ansible__config.modules.ansible_builtin_user.uniques | product(['defined']) | list }}"
        logic: or
  sshd_config:
    selectattr:
      - when:
          - ['type', 'defined']
          - ['type', 'equalto', 'sshd_config']
          - ['name', 'defined']
          - ['value', 'defined']
  ssh_config:
    selectattr:
      - when:
          - ['type', 'defined']
          - ['type', 'equalto', 'ssh_config']
          - ['name', 'defined']
          - ['value', 'defined']
  ssh_config_module:
    selectattr:
      - when:
          - ['type', 'defined']
          - ['type', 'equalto', 'ssh_config_module']
          - ['host', 'defined']
  sudoers_file:
    selectattr:
      - when:
          - ['type', 'defined']
          - ['type', 'equalto', 'sudoers_file']
          - ['entry', 'defined']
  sudoers_module:
    selectattr:
      - when:
          - ['type', 'defined']
          - ['type', 'equalto', 'sudoers_module']
          - ['name', 'defined']

auth__groups_all: "{{ auth__all |
  aybarsm.helper.selectattr(__auth__config.groups.selectattr) |
  aybarsm.helper.unique_recursive(__ansible__config.modules.ansible_builtin_group.uniques) |
  default([]) }}"

# Use lists_mergeby to combine all sections and sort by name for better output readability
auth__users_all: "{{ [auth__default, auth__group, auth__host] |
  map('selectattr', 'type', 'defined') | map('selectattr', 'type', 'equalto', 'user') |
  map('aybarsm.helper.replace_aliases', __ansible__config.modules.ansible.builtin.user.aliases) |
  map('selectattr', 'name', 'defined') |
  community.general.lists_mergeby('name', recursive=false, list_merge='prepend') |
  sort(attribute='name') | default([]) }}"

auth__authorized_keys_all: "{{ auth__all |
  aybarsm.helper.selectattr(__auth__config.authorized_keys.selectattr) |
  aybarsm.helper.unique_combinations([['user', 'key']]) |
  default([]) }}"

# Sort name and value to avoid unneccessary changes
auth__sshd_config_all: "{{ auth__all |
  aybarsm.helper.selectattr(__auth__config.sshd_config.selectattr) |
  aybarsm.helper.unique_combinations([['name', 'value']]) |
  sort(attribute='value', reverse=true) | sort(attribute='name', reverse=false) |
  default([]) }}"

# Sort name and value to avoid unneccessary changes
auth__ssh_config_all: "{{ auth__all |
  aybarsm.helper.selectattr(__auth__config.ssh_config.selectattr) |
  aybarsm.helper.unique_combinations([['name', 'value']]) |
  sort(attribute='value', reverse=true) | sort(attribute='name', reverse=false) |
  default([]) }}"

auth__ssh_config_module_all: "{{ auth__all |
  aybarsm.helper.selectattr(__auth__config.ssh_config_module.selectattr) |
  aybarsm.helper.unique_recursive('host') |
  default([]) }}"

auth__sudoers_file_all: "{{ auth__all |
  aybarsm.helper.selectattr(__auth__config.sudoers_file.selectattr) |
  aybarsm.helper.unique_recursive('entry') |
  default([]) }}"

auth__sudoers_module_all: "{{ auth__all |
  aybarsm.helper.selectattr(__auth__config.sudoers_module.selectattr) |
  aybarsm.helper.unique_recursive('name') |
  default([]) }}"

__auth__key_distribute_query: "*.auth__users_apply.results[*] | [] |
  [?contains(not_null(item.distribute_ssh_key,``),`{{ inventory_hostname }}`)].{user: name, key: ssh_public_key}"