pkg_mgr__all: "{{ {'host': pkg_mgr__host, 'group': pkg_mgr__group, 'default': pkg_mgr__default} | aybarsm.helper.role_items(only=pkg_mgr__use_only) }}"

__pkg_mgr__use_apt: "{{ ansible_os_family | default('') | lower == 'debian' and pkg_mgr__package_module == 'specific' }}"

# pkg_mgr__packages: "{{ pkg_mgr__all | selectattr('_type', 'eq', 'package') }}"
# pkg_mgr__repo_keys: "{{ pkg_mgr__all | selectattr('_type', 'eq', 'repo_key') }}"
# pkg_mgr__repos: "{{ pkg_mgr__all | selectattr('_type', 'eq', 'repo') }}"
# pkg_mgr__repo_lists: "{{ pkg_mgr__all | selectattr('_type', 'eq', 'repo_list') }}"