---
- name: Assert conditions as disk size calculation requested
  ansible.builtin.assert:
    that:
      - qemu_disk.state | default('', true) == 'resized'
      - qemu_disk.size is defined
      - qemu_disk.disk is defined
      - qemu_disk.size is match('^(\\d+)([A-Za-z]+)$')
    fail_msg: "Disk size calculation requested but state is not resized or size is not defined in correct format."
    success_msg: "Disk size calculation requested and state is resized and size is defined in correct format."
  register: proxmox__assert_qemu_disk_calc_size
  when: qemu_disk._calc_size| default(false, true)

- name: Include VM Info Task if calculation requested and conditions are met
  ansible.builtin.include_tasks:
    file: info/vm.yml
  vars:
    vm_info: "{{ qemu_disk | combine({'config': 'current'}) }}"
  when:
    - qemu_disk._calc_size| default(false, true)
    - proxmox__assert_qemu_disk_calc_size is success

- name: Proxmox QEMU DISK
  community.general.proxmox_disk:
    aio: "{{ qemu_disk.aio | default(omit, true) }}"
    api_host: "{{ qemu_disk.api_host }}"
    api_password: "{{ qemu_disk.api_password | default(omit, true) }}"
    api_port: "{{ qemu_disk.api_port | default(omit, true) }}"
    api_token_id: "{{ qemu_disk.api_token_id | default(omit, true) }}"
    api_token_secret: "{{ qemu_disk.api_token_secret | default(omit, true) }}"
    api_user: "{{ qemu_disk.api_user }}"
    backup: "{{ qemu_disk.backup | default(omit, true) }}"
    bps_max_length: "{{ qemu_disk.bps_max_length | default(omit, true) }}"
    bps_rd_max_length: "{{ qemu_disk.bps_rd_max_length | default(omit, true) }}"
    bps_wr_max_length: "{{ qemu_disk.bps_wr_max_length | default(omit, true) }}"
    bwlimit: "{{ qemu_disk.bwlimit | default(omit, true) }}"
    cache: "{{ qemu_disk.cache | default(omit, true) }}"
    create: "{{ qemu_disk.create | default(omit, true) }}"
    cyls: "{{ qemu_disk.cyls | default(omit, true) }}"
    delete_moved: "{{ qemu_disk.delete_moved | default(omit, true) }}"
    detect_zeroes: "{{ qemu_disk.detect_zeroes | default(omit, true) }}"
    dsicard: "{{ qemu_disk.dsicard | default(omit, true) }}"
    disk: "{{ qemu_disk.disk }}"
    format: "{{ qemu_disk.format | default(omit, true) }}"
    heads: "{{ qemu_disk.heads | default(omit, true) }}"
    import_from: "{{ qemu_disk.import_from | default(omit, true) }}"
    iops: "{{ qemu_disk.iops | default(omit, true) }}"
    iops_max: "{{ qemu_disk.iops_max | default(omit, true) }}"
    iops_max_length: "{{ qemu_disk.iops_max_length | default(omit, true) }}"
    iops_rd: "{{ qemu_disk.iops_rd | default(omit, true) }}"
    iops_rd_max: "{{ qemu_disk.iops_rd_max | default(omit, true) }}"
    iops_rd_max_length: "{{ qemu_disk.iops_rd_max_length | default(omit, true) }}"
    iops_wr: "{{ qemu_disk.iops_wr | default(omit, true) }}"
    iops_wr_max: "{{ qemu_disk.iops_wr_max | default(omit, true) }}"
    iops_wr_max_length: "{{ qemu_disk.iops_wr_max_length | default(omit, true) }}"
    iothread: "{{ qemu_disk.iothread | default(omit, true) }}"
    iso_image: "{{ qemu_disk.iso_image | default(omit, true) }}"
    mbps: "{{ qemu_disk.mbps | default(omit, true) }}"
    mbps_max: "{{ qemu_disk.mbps_max | default(omit, true) }}"
    mbps_rd: "{{ qemu_disk.mbps_rd | default(omit, true) }}"
    mbps_rd_max: "{{ qemu_disk.mbps_rd_max | default(omit, true) }}"
    mbps_wr: "{{ qemu_disk.mbps_wr | default(omit, true) }}"
    mbps_wr_max: "{{ qemu_disk.mbps_wr_max | default(omit, true) }}"
    media: "{{ qemu_disk.media | default(omit, true) }}"
    name: "{{ qemu_disk.name | default(omit, true) }}"
    queues: "{{ qemu_disk.queues | default(omit, true) }}"
    replicate: "{{ qemu_disk.replicate | default(omit, true) }}"
    rerror: "{{ qemu_disk.rerror | default(omit, true) }}"
    ro: "{{ qemu_disk.ro | default(omit, true) }}"
    scsiblock: "{{ qemu_disk.scsiblock | default(omit, true) }}"
    secs: "{{ qemu_disk.secs | default(omit, true) }}"
    serial: "{{ qemu_disk.serial | default(omit, true) }}"
    shared: "{{ qemu_disk.shared | default(omit, true) }}"
    size: "{{ resolved_size | default(qemu_disk.size | default(omit, true), true) }}"
    snapshot: "{{ qemu_disk.snapshot | default(omit, true) }}"
    ssd: "{{ qemu_disk.ssd | default(omit, true) }}"
    state: "{{ qemu_disk.state | default(omit, true) }}"
    storage: "{{ qemu_disk.storage | default(omit, true) }}"
    target_disk: "{{ qemu_disk.target_disk | default(omit, true) }}"
    target_storage: "{{ qemu_disk.target_storage | default(omit, true) }}"
    target_vmid: "{{ qemu_disk.target_vmid | default(omit, true) }}"
    timeout: "{{ qemu_disk.timeout | default(omit, true) }}"
    trans: "{{ qemu_disk.trans | default(omit, true) }}"
    validate_certs: "{{ qemu_disk.validate_certs | default(omit, true) }}"
    vmid: "{{ qemu_disk.vmid | default(omit, true) }}"
    werror: "{{ qemu_disk.werror | default(omit, true) }}"
    wwn: "{{ qemu_disk.wwn | default(omit, true) }}"
  vars:
    is_resolve_request: "{{ (qemu_disk._calc_size| default(false, true)) and 
      proxmox__assert_qemu_disk_calc_size is success and
      proxmox__info_vm.proxmox_vms[0][qemu_disk.disk] is defined }}"
    current_size: "{{ (proxmox__info_vm.proxmox_vms[0][qemu_disk.disk] | regex_search('size=(\\w+)(,|$)', '\\1') | first) if is_resolve_request else undef() }}"
    current_bytes: "{{ (current_size | human_to_bytes) if is_resolve_request else undef() }}"
    wanted_bytes: "{{ (qemu_disk.size | human_to_bytes) if is_resolve_request else undef() }}"
    diff_bytes: "{{ (wanted_bytes | int) - (current_bytes | int) if is_resolve_request else undef() }}"
    is_eligible: "{{ (diff_bytes | int > 0) if is_resolve_request else false }}"
    diff_size: "{{ (diff_bytes | int | human_readable) if is_eligible else undef() }}"
    diff_size_format: "{{ (diff_size | regex_search('(\\d+)\\.(\\d+)\\s([A-Za-z])', '\\1', '\\2', '\\3')) if is_eligible else undef() }}"
    resolved_size: "{{ ('+' + (diff_size_format | first) + (diff_size_format | last)) if is_eligible else undef() }}"
  register: proxmox__apply_qemu_disk