---
- name: Ensure ansible local facts directory exists on host
  become: true
  ansible.builtin.file:
    state: directory
    recurse: true
    path: "{{ ansible__local_facts_dir }}"
  register: ansible__ensure_local_facts_dir

- name: Import assign host local facts tasks
  ansible.builtin.import_tasks:
    file: assign_local_facts.yml
  vars:
    ansible__updated_local_facts: "{{ ansible_local[__ansible__local_fact_name] | default({}) }}"