---
- name: Manage system packages with common package manager
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    use: "{{ item.use | default(omit) }}"
  register: pkg_mgr__packages_common_apply
  when:
    - pkg_mgr__packages_all | type_debug == 'list'
    - pkg_mgr__packages_all | length > 0
  loop: "{{ pkg_mgr__packages_all }}"
