---
- name: Settle local facts on host if changed
  become: true
  ansible.builtin.template:
    src: "{{ ansible__local_fact_template }}"
    dest: "{{ ansible__local_fact_file }}"
    backup: "{{ ansible__local_fact_backup | default(omit) | bool }}"
  register: ansible__local_facts_settle
  listen: "ansible__local_facts_settle"
  notify: "ansible__local_facts_reread"

- name: Re-read local facts on the host
  become: true
  ansible.builtin.setup:
    filter: ansible_local
  register: ansible__local_facts_reread
  listen: "ansible__local_facts_reread"
  notify: ansible__local_facts_assign

- name: Assign host local facts to ansible facts
  ansible.builtin.set_fact:
    ansible__local_facts: "{{ ansible_local[ansible__local_fact_name] }}"
  register: ansible__local_facts_assign
  listen: "ansible__local_facts_assign"
  when:
    - ansible__local_fact_name is defined
    - ansible_local[ansible__local_fact_name] is defined