---
- name: Settle local facts on host if changed
  become: true
  ansible.builtin.template:
    src: "{{ ansible__local_fact_template }}"
    dest: "{{ ansible__local_fact_file }}"
    backup: "{{ ansible__local_fact_backup | default(omit) | bool }}"
  register: ansible__settle_local_facts
  listen: "ansible__settle_local_facts"
  when:
    - linux_role_ansible_enabled | bool
    - linux_role_ansible_manage_local_facts | bool