---
- name: Deploy grub.cfg
  become: true
  ansible.builtin.template:
    src: "{{ grub__template }}"
    dest: "{{ grub__destination }}"
    backup: "{{ grub__backup | default(omit) | bool }}"
    mode: "0644"
  when:
    - grub__all | type_debug == 'list'
    - grub__all | length > 0
  register: grub__deploy
  notify: grub__apply_changes_by_command
