---
- name: Deploy grub.cfg
  become: true
  ansible.builtin.template:
    src: "{{ linux_grub_template }}"
    dest: "{{ linux_grub_destination }}"
    backup: "{{ linux_grub_backup | default(omit) | bool }}"
    mode: "0644"
  when:
    - linux_grub_all | type_debug == 'list'
    - linux_grub_all | length > 0
  register: linux_grub_deploy
  notify: linux_grub_apply_changes_by_command
