---
# Required for configuration management
- name: Load aybarsm ansible role main variables
  ansible.builtin.include_vars: ../ansible/vars/main.yml

- name: Include grub tasks
  ansible.builtin.include_tasks:
    file: grub.yml
  when: grub__role_enabled | default(false) | bool
